name: Run tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
      - run: julia --project="." -e 'using Pkg; Pkg.instantiate(); Pkg.add(url="https://github.com/ismedina/MultiScaleOT.jl", rev="main"); Pkg.develop(PackageSpec(path=pwd()));'
      - uses: julia-actions/julia-runtest@master
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1